### ISSUE TITLE
Style the blog page

### ISSUE THREAD

**Issue by IonicaBizau** [Bloggify/newww#7]
📝 Docs here: https://github.com/Bloggify/bloggify.github.io/tree/app#bloggifygithubio

/cc @Bloggify/developers

**Comment by IonicaBizau** [comment]
You can change these:
- https://github.com/Bloggify/bloggify.github.io/blob/app/bloggify/theme/includes/blog-article.ajs
- https://github.com/Bloggify/bloggify.github.io/blob/app/bloggify/theme/public/css/custom.css
- https://github.com/Bloggify/bloggify.github.io/blob/9dfa7ea370143864212a5004e656d31e579144f7/bloggify/theme/blog-page.ajs#L1-L7

Feel free to experiment and play around. 🚀

**Comment by praveenscience** [comment]
:+1:

**Comment by IonicaBizau** [comment]
I will take care of this. ❇️
