### ISSUE TITLE
Check grammar on the dev website

### ISSUE THREAD

**Issue by IonicaBizau** [Bloggify/newww#8]
📝

**Comment by IonicaBizau** [comment]
### Things to review

Click the 📝 icon to edit it. 😁 

| URL | Source |  |
| --- | --- | --- |
| http://dev.bloggify.org | [📝](https://github.com/Bloggify/bloggify.github.io/blob/app/content/pages/_home.md) |  |
| http://dev.bloggify.org/logos | [📝](https://github.com/Bloggify/bloggify.github.io/blob/app/content/pages/logos.md) | Click the _Learn more_ button |
| http://dev.bloggify.org/blog/1-hello-world | [📝](https://github.com/Bloggify/bloggify.github.io/blob/app/content/articles/1.md) |  |

### How to edit

Use the edit button (✏️) directly on GitHub:

> ![bloggify_github_io_1_md_at_app_ _bloggify_bloggify_github_io](https://cloud.githubusercontent.com/assets/2864371/18816158/0c2950ea-834c-11e6-8115-103f45019f95.png)

**Comment by praveenscience** [comment]
Looks almost good. Will try to correct them if I find something needs to be changed.

**Comment by IonicaBizau** [comment]
:+1:
